AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  skicyclerunAPI: function library
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    MemorySize: 3008
    Environment:
      Variables:
        ALLOWED_ORIGINS: { Ref: AllowedOrigins }
    

Parameters:
  UserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool for authorizing protected routes
  AllowedOrigins:
    Type: String
    Default: "https://skicyclerun.com,https://dev.skicyclerun.com,http://localhost:4321,https://localhost:4321"
    Description: Comma-separated list of allowed origins for CORS
  ProtectedContentBucket:
    Type: String
    Description: S3 bucket name that stores protected post bodies
  FunctionRoleArn:
    Type: String
    Default: arn:aws:iam::635874589224:role/service-role/skicyclerun_www_lambda_apex_role
    Description: Existing IAM Role ARN for Lambda functions (if provided, SAM Policies are ignored)

Resources:

  # CloudFront Function for URI rewriting (pretty URLs)
  UriRewriteFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: skicyclerun-uri-rewrite
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;

          // Skip if already requesting a file with extension
          if (uri.includes('.')) {
            return request;
          }

          // Add index.html to directory requests
          if (uri.endsWith('/')) {
            request.uri += 'index.html';
          } else {
            // Add trailing slash and index.html for pretty URLs
            request.uri += '/index.html';
          }

          return request;
        }
      FunctionConfig:
        Comment: "Rewrite pretty URLs to index.html for skicyclerun.com"
        Runtime: cloudfront-js-2.0

  PublicApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: { Ref: UserPoolArn }
            Identity:
              Header: Authorization

  EchoEchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: EchoEcho/
      Handler: app.lambdaHandler
      # No explicit policies needed; SAM will create a basic execution role
      Events:
        Welcome:
          Type: Api
          Properties:
            Path: /echoecho
            Method: get
            RestApiId: { Ref: PublicApi }
        WelcomeOptions:
          Type: Api
          Properties:
            Path: /echoecho
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 3008
      Timeout: 30

  WelcomeMsgFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WelcomeMsg/
      Handler: app.lambdaHandler
      # No explicit policies needed; SAM will create a basic execution role
      Events:
        Welcome:
          Type: Api
          Properties:
            Path: /welcome
            Method: get
            RestApiId: { Ref: PublicApi }
        WelcomeOptions:
          Type: Api
          Properties:
            Path: /welcome
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 3008
      Timeout: 30

  RandomFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: RandomNumber/
      Handler: app.lambdaHandler
      # No explicit policies needed; SAM will create a basic execution role
      Events:
        Welcome:
          Type: Api
          Properties:
            Path: /random
            Method: get
            RestApiId: { Ref: PublicApi }
        WelcomeOptions:
          Type: Api
          Properties:
            Path: /random
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 3008
      Timeout: 30

  GetBucketKeyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getBucketkey/
      Handler: app.lambdaHandler
      Policies:
        - S3ReadPolicy:
            BucketName: { Ref: ProtectedContentBucket }
      Events:
        Welcome:
          Type: Api
          Properties:
            Path: /getkey
            Method: get
            RestApiId: { Ref: PublicApi }
        WelcomeOptions:
          Type: Api
          Properties:
            Path: /getkey
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 3008
      Timeout: 30

  GetAlbumsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getAlbums/
      Handler: app.lambdaHandler
      Policies:
        - S3ReadPolicy:
            BucketName: { Ref: ProtectedContentBucket }
      Events:
        Welcome:
          Type: Api
          Properties:
            Path: /getalbums
            Method: get
            RestApiId: { Ref: PublicApi }
        WelcomeOptions:
          Type: Api
          Properties:
            Path: /getalbums
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 3008
      Timeout: 30

  GetAlbumPhotosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getPhotos/
      Handler: app.lambdaHandler
      Policies:
        - S3ReadPolicy:
            BucketName: { Ref: ProtectedContentBucket }
      Events:
        Welcome:
          Type: Api
          Properties:
            Path: /getphotos
            Method: get
            RestApiId: { Ref: PublicApi }
        WelcomeOptions:
          Type: Api
          Properties:
            Path: /getphotos
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 3008
      Timeout: 30

  GetAlbumPhotosRNDFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getPhotosRandom/
      Handler: app.lambdaHandler
      Policies:
        - S3ReadPolicy:
            BucketName: { Ref: ProtectedContentBucket }
      Events:
        Welcome:
          Type: Api
          Properties:
            Path: /getphotosrandom
            Method: get
            RestApiId: { Ref: PublicApi }
        WelcomeOptions:
          Type: Api
          Properties:
            Path: /getphotosrandom
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 3008
      Timeout: 30

  StatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Status/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          ALLOWED_ORIGINS: { Ref: AllowedOrigins }
      Events:
        Status:
          Type: Api
          Properties:
            Path: /status
            Method: get
            RestApiId: { Ref: PublicApi }
        StatusOptions:
          Type: Api
          Properties:
            Path: /status
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 512
      Timeout: 10

  ProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Profile/
      Handler: app.lambdaHandler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminGetUser
              Resource: { Ref: UserPoolArn }
      Environment:
        Variables:
          ALLOWED_ORIGINS: { Ref: AllowedOrigins }
          USER_POOL_ID: "us-west-2_nkPiRBTSr"
      Events:
        Profile:
          Type: Api
          Properties:
            Path: /profile
            Method: get
            RestApiId: { Ref: PublicApi }
            Auth:
              Authorizer: CognitoAuthorizer
        ProfileOptions:
          Type: Api
          Properties:
            Path: /profile
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 512
      Timeout: 10

  ProtectedPostsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ProtectedPosts/
      Handler: app.lambdaHandler
      Policies:
        - DynamoDBReadPolicy:
            TableName: { Ref: ProtectedPostsTable }
        - S3ReadPolicy:
            BucketName: { Ref: ProtectedContentBucket }
      Environment:
        Variables:
          ALLOWED_ORIGINS: { Ref: AllowedOrigins }
          PROTECTED_BUCKET: { Ref: ProtectedContentBucket }
          PROTECTED_POSTS_TABLE: { Ref: ProtectedPostsTable }
      Events:
        List:
          Type: Api
          Properties:
            Path: /protected/posts
            Method: get
            RestApiId: { Ref: PublicApi }
            Auth:
              Authorizer: CognitoAuthorizer
        Detail:
          Type: Api
          Properties:
            Path: /protected/posts/{slug}
            Method: get
            RestApiId: { Ref: PublicApi }
            Auth:
              Authorizer: CognitoAuthorizer
        ListOptions:
          Type: Api
          Properties:
            Path: /protected/posts
            Method: options
            RestApiId: { Ref: PublicApi }
        DetailOptions:
          Type: Api
          Properties:
            Path: /protected/posts/{slug}
            Method: options
            RestApiId: { Ref: PublicApi }
      MemorySize: 1024
      Timeout: 20

  ProtectedPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH


Outputs:
  PublicApiBaseUrl:
    Description: Base URL for the public API
    Value:
      Fn::Sub: "https://${PublicApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: PublicApiBaseUrl

  UriRewriteFunctionArn:
    Description: ARN of the CloudFront URI rewrite function
    Value: !GetAtt UriRewriteFunction.FunctionMetadata.FunctionARN
    Export:
      Name: UriRewriteFunctionArn
